name: Pylint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        find . -type f -name "*.py" | xargs pylint --disable=import-error,no-name-in-module,no-member,too-few-public-methods,too-few-public-methods,broad-except,unused-argument,redefined-outer-name,invalid-name,import-outside-toplevel,duplicate-code,no-else-return,inconsistent-return-statements,relative-beyond-top-level,protected-access,bare-except,fixme,anomalous-backslash-in-string,too-many-arguments,too-many-branches,too-many-instance-attributes --max-line-length=150
